packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - '@uni-helper/unocss-preset-uni'
  - core-js
  - es5-ext
  - esbuild
  - less
  - prisma
  - protobufjs
  - vue-demi
